### ISSUE TITLE
handle google cloud auth errors 

### ISSUE THREAD

**Issue by SoryRawyer** [SoryRawyer/monty#10]
```
(monty) rory@rory:~/dev/monty$ python launch_player.py 
Traceback (most recent call last):
  File "launch_player.py", line 92, in <module>
    main()
  File "launch_player.py", line 20, in main
    client = CloudStorage()
```
handle errors that could arise from not being able to access Google Cloud and do something useful with them, like display something next to non-local files to say that you can't get to em.
Whatever happens, though, a user should still be able to run the player.

**Comment by ablwr** [comment]
:+1:

**Comment by SoryRawyer** [comment]
This should be handled by calling something like `cloud.new()` and getting either a client that doesn't do anything or a client that has a connection to google cloud.

Also maybe rename this module to storage, or something more accurate than `cloud`.
